### PR TITLE
Feature / integration specs and solving n+1 problem

### PR DESCRIPTION
**Pull request by John-Kibirige**
### In this milestone, I worked on the following 
- N+1 problem is solved when fetching all posts and their comments for a user
- Use Capybara to write integration tests for each of the following views
    - User index page
    - Users show  page 
    - User post index page
    - User post show page

### CODE REVIEW

**Review by FrederickMih — CHANGES_REQUESTED** [review]
## Hi :raising_hand: @John-Kibirige, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

- Added featured tests for all pages :+1: 
- All tests cases passed :heavy_check_mark: 


## Required Changes ♻️

- [ ] As requested from the requirements, let's kindly resolve the N+1 query problem to avoid fetching nth queries from the database when fetching all posts and their comments. This will also improve performance.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by FrederickMih** [comment]
Hi @John-Kibirige, it seems you used bullet to resolve the N+1 query issue.

**Comment by FrederickMih** [comment]
@John-Kibirige  kindly used **includes** to resolve the N+1 query problem not bullet

**Review by Munsa1 — APPROVED** [review]
Hi @John-Kibirige, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
